---
- name: Install Kubernetes
  hosts: all
  gather_facts: false
  remote_user: packer
  become: true
  vars:
    docker_yum_repo_url: https://download.docker.com/linux/centos/docker-ce.repo
    kubernetes_packages:
      - name: kubelet-1.13.1
        state: present
      - name: kubectl-1.13.1
        state: present
      - name: kubeadm-1.13.1
        state: present
      - name: kubernetes-cni-0.6.0
        state: present

  tasks:
    # Base image built-in adjustements
    - name: Disable yum-cron to avoid uncontrolled updates
      systemd:
        name: yum-cron
        state: stopped
        enabled: false

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    # Install Docker
    - name: Add Docker GPG key
      rpm_key:
        key: https://download.docker.com/linux/centos/gpg
        state: present

    - name: Add Docker repository
      get_url:
        url: "{{ docker_yum_repo_url }}"
        dest: '/etc/yum.repos.d/docker-ce.repo'
        owner: root
        group: root
        mode: 0644

    - name: Install Docker
      package:
        name: docker-ce-18.06.1.ce
        state: present

    - name: Ensure Docker is started and enabled at boot
      service:
        name: docker
        state: started
        enabled: true

    # Install Kubernetes
    - name: Ensure Kubernetes repository exists
      yum_repository:
        name: kubernetes
        description: Kubernetes
        enabled: true
        gpgcheck: true
        repo_gpgcheck: true
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Add Kubernetes GPG keys
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - https://packages.cloud.google.com/yum/doc/yum-key.gpg
        - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

    - name: Install Kubernetes packages
      package:
        name: "{{ item.name | default(item) }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ kubernetes_packages }}"

    - name: Set IP Tables config for Kubernetes Networking
      sysctl:
        name: net.bridge.bridge-nf-call-iptables
        value: 1
        state: present
